- name: create a bucket
  hosts: localhost
  gather_facts: no
  connection: local
  
  tasks:
   - gcp_storage_bucket:
       name: ansible-storage-module
       project: "cp-esc-commvault-dev"
       auth_kind: "service_account"
       state: present
       
