- name: create a project
  hosts: localhost
  gather_facts: no
  connection: local
  
  tasks:
  - gcp_resourcemanager_project:
     name: "{{ gcp_project_name }}"
     id: "{{ gcp_project_name }}"
#    auth_kind: serviceaccount
#    service_account_file: "/tmp/auth.pem"
     parent:
      type: organization
      id: 775078138164
     state: present
